sonar.projectKey=bookingenginev2
sonar.projectName=TR V2
sonar.projectVersion=1.0

sonar.sources=apps,packages

sonar.tests=apps,packages
sonar.test.inclusions=**/test/**/*.ts,**/test/**/*.tsx,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/.turbo/**,**/.vite/**,**/storybook-static/**,**/generated/**,**/drizzle/**/*.sql,**/*.d.ts
sonar.test.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/.turbo/**

sonar.javascript.lcov.reportPaths=apps/*/coverage/lcov.info

sonar.qualitygate.wait=true