# GITLEAKS DOCKER COMPOSE
name: gitleaks

services:

  # SCAN WITHOUT GIT HISTORY
  gitleaks:
    image: ghcr.io/gitleaks/gitleaks:v8.30.1
    profiles:
      - security
    volumes:
      - ${STACK_PROJECT_ROOT:-../..}:/repo:ro
      - ..:/stack:ro
    working_dir: /repo
    command:
      - detect
      - --source=/repo
      - --config=/stack/gitleaks/.gitleaks.toml
      - --gitleaks-ignore-path=/stack/gitleaks/.gitleaksignore
      - --no-git
      - --verbose

  # SCAN WITH GIT HISTORY
  gitleaks-history:
    image: ghcr.io/gitleaks/gitleaks:v8.30.1
    profiles:
      - security
    volumes:
      - ${STACK_PROJECT_ROOT:-../..}:/repo:ro
      - ..:/stack:ro
    working_dir: /repo
    command:
      - detect
      - --source=/repo
      - --config=/stack/gitleaks/.gitleaks.toml
      - --gitleaks-ignore-path=/stack/gitleaks/.gitleaksignore
      - --verbose
